### ISSUE TITLE
Does not work with emacs 26.0.91 RC ?

### ISSUE THREAD

**Issue by CSRaghunandan** [tumashu/company-childframe#12]
This is my version of emacs: `GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1212)) of 2018-02-26`

When I run `(company-childframe-mode 1)` I get a message `[Company-childframe]: Requires emacs (version >= 26.0.91)` ?

**Comment by tumashu** [comment]
it just a note,  just ignore it

**Comment by CSRaghunandan** [comment]
Cool
Please hide the message for emacs 26.091 or greater. It's confusing for users.

**Comment by tumashu** [comment]
When emacs 26 release, I will remove this note :-)

**Comment by CSRaghunandan** [comment]
Fair enough :) I'm not really up to date with the release cycles for emacs26.
When can we expect the stable release to be out? Considering emacs26 has been in RC for more than a month

**Comment by tumashu** [comment]
The real reason is that:  company-childframe require  child-frame feature of emacs26, If child-frame is not stable enough,  company-childframe will not be stable.

**Comment by tumashu** [comment]
company-childframe a  bug finder of child-frame at the moment, so it is unstable :-)
