### ISSUE TITLE
flicker on Unity (when the HiDPI on?)

### ISSUE THREAD

**Issue by tumashu** [tumashu/company-childframe#2]
https://user-images.githubusercontent.com/67725/34804759-4477f5ea-f6b5-11e7-8736-29ff95318a2c.gif

@dgutov Do yout have tested company-childframe with "emacs -Q" ?

**Comment by dgutov** [comment]
Yes: https://send.firefox.com/download/793d8dab0f/#ziyoHhB0usYUs4mBCp5Q0w

**Comment by tumashu** [comment]
@dgutov  Are you using Linux？  what about change a window-manager to test again, for  child-frame seem to deal with window-manager.

**Comment by dgutov** [comment]
I'll try when I have the time, but for now I only have Unity installed. If someone could try using Gnome 3 (the new default DE in Ubuntu), that would be great.

**Comment by tumashu** [comment]
I have updated the code, maybe it can *reduce* flicker  :-),  by the way, using company-childframe-mode instead of company-childframe-enable.

**Comment by dgutov** [comment]
Err, it is now positioned correctly *without* Robert's patch. Also, the popup position is cached too much: it's not updated if I just call `recenter-top-bottom` and invoke completion again.

And with Robert's patch applied, the popup is always positioned near the middle of the window. Very odd.

**Comment by tumashu** [comment]
```
it's not updated if I just call recenter-top-bottom and invoke completion again.
```

Cache method has been updated, try again.

**Comment by tumashu** [comment]
May be running multi  set-frame-position have some bug?

**Comment by dgutov** [comment]
> Cache method has been updated, try again.

Seems to work okay now, thanks!

> May be running multi set-frame-position have some bug?

Probably. Anyway, I'm guessing you'll have to make some more changes after Robert works on his patch some more (and its gets committed).

**Comment by tumashu** [comment]
I do not know,  the only big change for this problem is that run set-frame-position when needed

**Comment by tumashu** [comment]
Maybe you can try the below code to test :-)

```
(let ((test (let ((after-make-frame-functions nil))
              (make-frame
               `((parent-frame . ,(window-frame))
                 (width . 10)
                 (height . 10)
                 (mytest . t)))))
      (pos (posn-x-y (posn-at-point (point) (selected-window)))))
  (dotimes (i 10)
    (set-frame-position test (car pos) (cdr pos)))
  (sit-for 3)
  (dolist (frame (frame-list))
    (when (frame-parameter frame 'mytest)
      (delete-frame frame))))
```

**Comment by dgutov** [comment]
IDK, it's weird. First, it does flicker basically like that (except not at half coordinates, but at the top-left corner of the frame).

Sometimes there's only a flicker, though. And the popup doesn't appear in the end.

**Comment by tumashu** [comment]
```
but at the top-left corner of the frame
```
when child-frame is created init. it will be at top-left corner.

**Comment by dgutov** [comment]
I haven't seen any flickers in a while. Thank you, can probably close this.

**Comment by tumashu** [comment]
ok
