### ISSUE TITLE
Can we set the minor mode mode line indicator shorter to one letter?

### ISSUE THREAD

**Issue by xqliu** [tumashu/company-childframe#22]
Dear,

Can we set the minor mode mode line indicator to one letter? I think currently the minor mode indicator "company-childframe" is too long and used too much space in mode line.

I think normally only major mode will set the mode line indicator to a word, but minor mode normally set to something shorter, like one word.

感觉现在的状态栏minor mode标识有点太长了，占用了太大的空间

Thanks.

**Comment by tumashu** [comment]
可以，只要你能想出一个短名字

**Comment by xqliu** [comment]
叫CCF 怎么样

**Comment by tumashu** [comment]
Add a custom variable, set it by your self
