### ISSUE TITLE
set-frame-parameter a child-frame's 'parent-frame error on macOS ?

### ISSUE THREAD

**Issue by tumashu** [tumashu/company-childframe#3]
http://lists.gnu.org/archive/html/emacs-devel/2018-01/msg00372.html

**Comment by tumashu** [comment]
@aaronjensen  Do you have time to test this patch, and report its work status?  I can not do this job for I have no Mac ...

**Comment by aaronjensen** [comment]
Yep, that fixed it for me and bug#30019. Sweet 😄

**Comment by tumashu** [comment]
@aaronjensen  Suggest reply your test result to emacs-devel, which may let the patch merge quick :-)

**Comment by aaronjensen** [comment]
I replied on my bug, so Martin should see it there.

**Comment by aaronjensen** [comment]
@tumashu The patch has been added to emacs-26

**Comment by tumashu** [comment]
ok
