### ISSUE TITLE
child frame shows a weird first column with the default background

### ISSUE THREAD

**Issue by dgutov** [tumashu/company-childframe#6]
See the while column to the left of the popup contents. Is it intentional?

![screenshot from 2018-01-23 14-35-55](https://user-images.githubusercontent.com/271877/35273808-f22c7816-004a-11e8-8cfe-cbef2f49bdf0.png)

**Comment by tumashu** [comment]
No,  this may be a bug ...

![qq 20180124081454](https://user-images.githubusercontent.com/67725/35307684-cc86fde0-00de-11e8-8a87-58e88ef278c1.png)

**Comment by tumashu** [comment]
Can it be reproduced with "emacs -Q" ?

**Comment by dgutov** [comment]
Nope.

I'll try to see what part of my config triggers it.

**Comment by tumashu** [comment]
```
I'll try to see what part of my config triggers it.
```
May be some frame para setting.

**Comment by dgutov** [comment]
Doesn't look like it, so far.

**Comment by dgutov** [comment]
Found it!

Evaluate this before enabling `company-childframe-mode`:

```el
(setq-default left-fringe-width 16)
```

It overrides the frame parameter, apparently.

**Comment by dgutov** [comment]
Looks fixed, thanks!
